version: '2'
services:
  mariadb:
    container_name: replication
    restart: "no"
    build: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./config:/etc/mysql/conf.d
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD={MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE={MARIADB_DATABASE}
      - MARIADB_USER={MARIADB_USER}
      - MARIADB_PASSWORD={MARIADB_PASSWORD}

volumes:
  mariadb_data: